name: to_hex_string
description: A single extension on int to convert it to a proper hex string, since the Dart team stubbornly refuses to add it.
version: 1.0.1
homepage: https://github.com/Ampless/to_hex_string

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  tested: ^1.0.0
